### ISSUE TITLE
New *regular* node · WISE SECURITY GLOBAL

### ISSUE THREAD

**Issue by zigorwsg** [alastria/alastria-node-quorum-directory#19]
| WISE_ALASTRIA_DES | Self-Hosted (2C/4GB/100GB) | enode://2c3a651e11b1efc92dde94d1819ede90ef083875dd6365a5616281a9a5e76343cee6024219056c185ef52fcfb13fb4f1ad67a40a278f4649ada59e1fb84dede4@178.32.176.187:21000?discport=1439 |

**Comment by alejandroalffer** [comment]
Sorry for the Deleay. Node added and running with at least one peer:

```
root@e8cdc103b174:~# geth attach /root/alastria/data/geth.ipc --exec admin.peers|grep -i 40a278f464
 enode: "enode://2c3a651e11b1efc92dde94d1819ede90ef083875dd6365a5616281a9a5e76343cee6024219056c185ef52fcfb13fb4f1ad67a40a278f4649ada59e1fb84dede4@178.32.176.187:34594",
```

Best regards!
